"""add country and league code to table team

Revision ID: 34a682e292db
Revises: 2b83de701452
Create Date: 2026-08-19 15:24:16.309788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a682e292db'
down_revision: Union[str, Sequence[str], None] = '2b83de701452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('country', sa.String(length=50), nullable=False))
    op.add_column('teams', sa.Column('league_code', sa.String(length=10), nullable=False))
    op.create_index(op.f('ix_teams_country'), 'teams', ['country'], unique=False)
    op.create_index(op.f('ix_teams_league_code'), 'teams', ['league_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_league_code'), table_name='teams')
    op.drop_index(op.f('ix_teams_country'), table_name='teams')
    op.drop_column('teams', 'league_code')
    op.drop_column('teams', 'country')
    # ### end Alembic commands ###
