"""add CITEXT to teams

Revision ID: 3da9f0030ce1
Revises: 9db9a8a73592
Create Date: 2026-08-20 16:22:36.370710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da9f0030ce1'
down_revision: Union[str, Sequence[str], None] = '9db9a8a73592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS citext;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION IF EXISTS citext;")
    # ### end Alembic commands ###
