"""make_player_position_nullable

Revision ID: 459f05ce7272
Revises: c4cedb6be575
Create Date: 2026-08-25 11:01:55.873670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '459f05ce7272'
down_revision: Union[str, Sequence[str], None] = 'c4cedb6be575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'position',
               existing_type=postgresql.CITEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'position',
               existing_type=postgresql.CITEXT(),
               nullable=False)
    # ### end Alembic commands ###
