"""add indexes to player table

Revision ID: 57e4ef7dc9e6
Revises: 31e367797aaf
Create Date: 2026-08-20 15:02:04.026157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57e4ef7dc9e6'
down_revision: Union[str, Sequence[str], None] = '31e367797aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_players_nationality'), 'players', ['nationality'], unique=False)
    op.create_index(op.f('ix_players_position'), 'players', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_position'), table_name='players')
    op.drop_index(op.f('ix_players_nationality'), table_name='players')
    # ### end Alembic commands ###
