"""change player column to citext

Revision ID: 9db9a8a73592
Revises: dbd705d1e3ef
Create Date: 2026-08-20 15:51:01.419013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9db9a8a73592'
down_revision: Union[str, Sequence[str], None] = 'dbd705d1e3ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=postgresql.CITEXT(length=100),
               existing_nullable=False)
    op.alter_column('players', 'position',
               existing_type=sa.VARCHAR(length=50),
               type_=postgresql.CITEXT(length=50),
               existing_nullable=False)
    op.alter_column('players', 'nationality',
               existing_type=sa.VARCHAR(length=100),
               type_=postgresql.CITEXT(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'nationality',
               existing_type=postgresql.CITEXT(length=100),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('players', 'position',
               existing_type=postgresql.CITEXT(length=50),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('players', 'name',
               existing_type=postgresql.CITEXT(length=100),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
