"""add CITEXT to teams table

Revision ID: c4cedb6be575
Revises: 3da9f0030ce1
Create Date: 2026-08-20 16:24:10.780872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4cedb6be575'
down_revision: Union[str, Sequence[str], None] = '3da9f0030ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=postgresql.CITEXT(length=100),
               existing_nullable=False)
    op.alter_column('teams', 'country',
               existing_type=sa.VARCHAR(length=50),
               type_=postgresql.CITEXT(length=50),
               existing_nullable=False)
    op.alter_column('teams', 'league_code',
               existing_type=sa.VARCHAR(length=10),
               type_=postgresql.CITEXT(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'league_code',
               existing_type=postgresql.CITEXT(length=10),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('teams', 'country',
               existing_type=postgresql.CITEXT(length=50),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('teams', 'name',
               existing_type=postgresql.CITEXT(length=100),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
