"""add CITEXT 2

Revision ID: dbd705d1e3ef
Revises: a7d078595c5a
Create Date: 2026-08-20 15:48:53.719272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd705d1e3ef'
down_revision: Union[str, Sequence[str], None] = 'a7d078595c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS citext;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION IF EXISTS citext;")
    # ### end Alembic commands ###
